import type {
  CuriosityExploreNode,
  CuriositySource,
  CuriosityVisual,
} from "@curio/shared";

/**
 * Provider-neutral content generated by an AI provider.
 *
 * AI providers generate content.
 * Curio application logic owns publication/editorial state.
 */
export interface GeneratedCurio {
  hook: string;
  answer: string;
  explanation: string;
  quickFact?: string;

  tags: string[];
  concepts: string[];

  visual: CuriosityVisual;
  explore: CuriosityExploreNode[];
  sources: CuriositySource[];
}
